/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2015-11-26 11:55:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class reg_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("        <title>Inscrition</title>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("        <title>Inscription</title>\r\n");
      out.write("         <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t    <link href=\"http://netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"css/main.css\" />\r\n");
      out.write("\t    <script src=\"http://code.jquery.com/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("\t    <script src=\"http://netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t    <script src=\"js/parallax.js\"></script>\r\n");
      out.write("\t    <script src=\"http://mymaplist.com/js/vendor/TweenLite.min.js\"></script>\r\n");
      out.write("\t    <!--Pulling Awesome Font -->\r\n");
      out.write("\t\t<link href=\"//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("            <script type=\"text/javascript\">\r\n");
      out.write("\t\t    var a = Math.ceil(Math.random() * 10);\r\n");
      out.write("\t\t    var b = Math.ceil(Math.random() * 10);       \r\n");
      out.write("\t\t    var c = a + b\r\n");
      out.write("\t\t    function DrawBotBoot()\r\n");
      out.write("\t\t    {\r\n");
      out.write("\t\t        document.write(\"Quel est le resultat de \"+ a + \" + \" + b +\" ? \");\r\n");
      out.write("\t\t        // document.write(\"<input id='BotBootInput' type='text' maxlength='2' size='2'/>\");\r\n");
      out.write("\t\t    }    \r\n");
      out.write("\t\t    function ValidBotBoot(){\r\n");
      out.write("\t\t        var d = document.getElementById('BotBootInput').value;\r\n");
      out.write("\t\t        if (d == c) {document.getElementById('Validation').disabled = false }\r\n");
      out.write("\t\t        else document.getElementById('Validation').disabled = true;       \t\t        \r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t    </script>\r\n");
      out.write("    </head>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("\tbackground-image:url(\"http://www.wallpapers-hd.ovh/wp-content/uploads/2015/01/console-games-0367.jpg\");\r\n");
      out.write("}\r\n");
      out.write(".container {\r\n");
      out.write("    padding: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-login {\r\n");
      out.write("    background-color: #EDEDED;\r\n");
      out.write("    padding-top: 10px;\r\n");
      out.write("    padding-bottom: 20px;\r\n");
      out.write("    padding-left: 20px;\r\n");
      out.write("    padding-right: 20px;\r\n");
      out.write("    border-radius: 15px;\r\n");
      out.write("    border-color:#d2d2d2;\r\n");
      out.write("    border-width: 5px;\r\n");
      out.write("    width:50%;\r\n");
      out.write("    box-shadow:0 1px 0 #cfcfcf;\r\n");
      out.write("    box-shadow: 2px 2px 15px black;\r\n");
      out.write("    box-shadow: -1px 2px 10px 3px rgba(0, 0, 0, 0.3) inset;\r\n");
      out.write("    margin-left: auto;\r\n");
      out.write("    margin-right: auto;\r\n");
      out.write("    opacity:0.9;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h4 { \r\n");
      out.write(" border:0 solid #fff; \r\n");
      out.write(" border-bottom-width:1px;\r\n");
      out.write(" padding-bottom:10px;\r\n");
      out.write(" text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control {\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write(".header {\r\n");
      out.write("\tbackground-color: black;\r\n");
      out.write("\theight: 60px;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\ttop:0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer {\r\n");
      out.write("\tbottom:0;\r\n");
      out.write("\tleft:0;\r\n");
      out.write("\theight:40px;\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\tbackground: black;\r\n");
      out.write("\tposition:fixed;\r\n");
      out.write("}\r\n");
      out.write(".IgameLogo{\r\n");
      out.write("\ttop:0;\r\n");
      out.write("\tfloat:right;\r\n");
      out.write("\twidth: 60px;\r\n");
      out.write("\theight: 60px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("    <body>\r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("\t<div class=\"header\">\r\n");
      out.write("\t<img class=\"IgameLogo\" src=\"http://img11.hostingpics.net/pics/731672logoigamefondnoir.png\" alt=\"\">\r\n");
      out.write("\t\t<p style=\"padding-top:2px;\">\r\n");
      out.write("\t\t\t");

		    	if ((session.getAttribute("userid") == null) || (session.getAttribute("userid") == "")) {
			
      out.write("\r\n");
      out.write("\t\t\t\tVous n'êtes pas connecté<br/>\r\n");
      out.write("\t\t\t\t<a href=\"index\">Connectez vous!</a>\r\n");
      out.write("\t\t\t");

				} else {
			
      out.write("\r\n");
      out.write("\t\t\t\t<!-- NAVIGATION -->\r\n");
      out.write("\t\t\t\t<div class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-default dropdown-toggle\" type=\"button\" data-toggle=\"dropdown\">Bonjour ");
      out.print(session.getAttribute("userid"));
      out.write("\r\n");
      out.write("\t\t\t\t\t<span class=\"caret\"></span></button>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\">\t\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href='logout'>Déconnexion</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"edit\">Modifier profil</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /NAVIGATION -->\r\n");
      out.write("\t\t\t");

			  	}
			
      out.write("\t\r\n");
      out.write("\t\t</p>\t\r\n");
      out.write("    </div>\r\n");
      out.write("\t<!-- /Header -->\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("\t        <form method=\"get\" action=\"registration\" class=\"form-login\">\t            \r\n");
      out.write("\t            <!-- BOOTSTRAP -->\r\n");
      out.write("\t            <h4>Inscription</h4>\r\n");
      out.write("\t            <input type=\"text\" id=\"fname\" name=\"fname\" class=\"form-control input-sm chat-input\" placeholder=\"Prénom\" required pattern=\"\\b(?:(?!insta|test)\\w)+\\b\" title=\"Veuillez ne pas utiliser comme prenom : insta\" />\r\n");
      out.write("\t            </br>\r\n");
      out.write("\t            <input type=\"text\" id=\"lname\" name=\"lname\" class=\"form-control input-sm chat-input\"  placeholder=\"Nom\" required />\r\n");
      out.write("\t            </br>\r\n");
      out.write("\t            <input type=\"email\" id=\"email\" name=\"email\" class=\"form-control input-sm chat-input\"  placeholder=\"Email\" required />\r\n");
      out.write("\t            </br>\r\n");
      out.write("\t            <input type=\"text\" id=\"uname\" name=\"uname\" class=\"form-control input-sm chat-input\"  placeholder=\"Pseudo\" required />\r\n");
      out.write("\t            </br>\r\n");
      out.write("\t            <input type=\"password\" id=\"pass\" name=\"pass\" class=\"form-control input-sm chat-input\"  placeholder=\"Mot de passe\" required />\r\n");
      out.write("\t            </br>\r\n");
      out.write("\t            <p><script type=\"text/javascript\">DrawBotBoot()</script></p>\r\n");
      out.write("\t            <input id='BotBootInput' type='text' maxlength='2' size='2' onChange=\"ValidBotBoot();\" />\r\n");
      out.write("\t            <div class=\"wrapper\">\r\n");
      out.write("\t\t            <span class=\"group-btn\">  \r\n");
      out.write("\t\t            \t</br>   \r\n");
      out.write("\t\t                <input id=\"Validation\" type=\"submit\" class=\"btn btn-primary btn-md\" value=\"Valider\" disabled=\"disabled\" />\r\n");
      out.write("\t\t                <input type=\"reset\" class=\"btn btn-primary btn-md\" value=\"Annuler\" />\r\n");
      out.write("\t\t            </span>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <!-- BOOTSTRAP -->\r\n");
      out.write("\t            \r\n");
      out.write("\t            \r\n");
      out.write("\t            <!--<table border=\"1\" width=\"30%\" cellpadding=\"5\">\r\n");
      out.write("\t                <thead>\r\n");
      out.write("\t                    <tr>\r\n");
      out.write("\t                        <th colspan=\"2\">S'inscrire</th>\r\n");
      out.write("\t                    </tr>\r\n");
      out.write("\t                </thead>\r\n");
      out.write("\t                <tbody>\r\n");
      out.write("\t                    <tr>\r\n");
      out.write("\t                        <td>Prénom</td>\r\n");
      out.write("\t                        <td><input type=\"text\" name=\"fname\" value=\"\" required pattern=\"\\b(?:(?!insta|test)\\w)+\\b\" title=\"Veuillez ne pas utiliser comme prenom : insta\"/></td>\r\n");
      out.write("\t                    </tr>\r\n");
      out.write("\t                    <tr>\r\n");
      out.write("\t                        <td>Nom</td>\r\n");
      out.write("\t                        <td><input type=\"text\" name=\"lname\" value=\"\" required/></td>\r\n");
      out.write("\t                    </tr>\r\n");
      out.write("\t                    <tr>\r\n");
      out.write("\t                        <td>Email</td>\r\n");
      out.write("\t                        <td><input type=\"text\" name=\"email\" value=\"\" required/></td>\r\n");
      out.write("\t                    </tr>\r\n");
      out.write("\t                    <tr>\r\n");
      out.write("\t                        <td>Pseudo</td>\r\n");
      out.write("\t                        <td><input type=\"text\" name=\"uname\" value=\"\" required/></td>\r\n");
      out.write("\t                    </tr>\r\n");
      out.write("\t                    <tr>\r\n");
      out.write("\t                        <td>Mot de passe</td>\r\n");
      out.write("\t                        <td><input type=\"password\" name=\"pass\" value=\"\" required/></td>\r\n");
      out.write("\t                    </tr>\r\n");
      out.write("\t                    <tr>\r\n");
      out.write("\t                        <td>Combien font <script type=\"text/javascript\">DrawBotBoot()</script> ?</td>\r\n");
      out.write("\t                        <td><input id='BotBootInput' type='text' maxlength='2' size='2' onChange=\"ValidBotBoot();\" /></td>\r\n");
      out.write("\t                          <td><script type=\"text/javascript\">DrawBotBoot()</script>  \r\n");
      out.write("\t                    </tr>\r\n");
      out.write("\t                    <tr>\r\n");
      out.write("\t                        <td><input id=\"Validation\" type=\"submit\" value=\"Valider\" disabled=\"disabled\"/></td>\r\n");
      out.write("\t                        <td><input type=\"reset\" value=\"Annuler\" /></td>\r\n");
      out.write("\t                    </tr>\r\n");
      out.write("\t                    <tr>\r\n");
      out.write("\t                        <td colspan=\"2\">Pas encore inscrit <a href=\"index\">S'inscrire</a></td>\r\n");
      out.write("\t                    </tr>\r\n");
      out.write("\t                </tbody>\r\n");
      out.write("\t            </table>-->\r\n");
      out.write("\t        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Footer -->\r\n");
      out.write("        <div class=\"footer\">\r\n");
      out.write("        <p style=\"text-align:center;\" class=\"text-muted\">I-GAME© by T2ISOFT : <a href=\"http://www.t2isoft.com\">www.t2isoft.com</a></p>\r\n");
      out.write("      </div>  \r\n");
      out.write("<!-- /Footer -->\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
