/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2015-11-27 14:43:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class success_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("        <title>Liste des jeux</title>\r\n");
      out.write("         <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t    <link href=\"http://netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"css/main.css\" />\r\n");
      out.write("\t    <script src=\"http://code.jquery.com/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("\t    <script src=\"http://netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t    <script src=\"js/parallax.js\"></script>\r\n");
      out.write("\t    <script src=\"http://mymaplist.com/js/vendor/TweenLite.min.js\"></script>\r\n");
      out.write("\t    <!--Pulling Awesome Font -->\r\n");
      out.write("\t\t<link href=\"//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    </head>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("\tbackground-image:url(\"http://www.wallpapers-hd.ovh/wp-content/uploads/2015/01/console-games-0367.jpg\");\r\n");
      out.write("}\r\n");
      out.write(".header {\r\n");
      out.write("\tbackground-color: black;\r\n");
      out.write("\theight: 60px;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\ttop:0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer {\r\n");
      out.write("\tbottom:0;\r\n");
      out.write("\tleft:0;\r\n");
      out.write("\theight:40px;\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\tbackground: black;\r\n");
      out.write("}\r\n");
      out.write(".page-header{\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".IgameLogo{\r\n");
      out.write("\ttop:0;\r\n");
      out.write("\tfloat:right;\r\n");
      out.write("\twidth: 60px;\r\n");
      out.write("\theight: 60px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- Header -->\r\n");
      out.write("\t<div class=\"header\">\r\n");
      out.write("\t<img class=\"IgameLogo\" src=\"http://img11.hostingpics.net/pics/731672logoigamefondnoir.png\" alt=\"\">\r\n");
      out.write("\t\t<p style=\"padding-top:2px;\">\r\n");
      out.write("\t\t\t");

		    	if ((session.getAttribute("userid") == null) || (session.getAttribute("userid") == "")) {
			
      out.write("\r\n");
      out.write("\t\t\t\tVous n'êtes pas connecté<br/>\r\n");
      out.write("\t\t\t\t<a href=\"index\">Connectez vous!</a>\r\n");
      out.write("\t\t\t");

				} else {
			
      out.write("\r\n");
      out.write("\t\t\t\t<!-- NAVIGATION -->\r\n");
      out.write("\t\t\t\t<div class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-default dropdown-toggle\" type=\"button\" data-toggle=\"dropdown\">Bonjour ");
      out.print(session.getAttribute("userid"));
      out.write("\r\n");
      out.write("\t\t\t\t\t<span class=\"caret\"></span></button>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\">\t\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href='logout'>Déconnexion</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"edit\">Modifier profil</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /NAVIGATION -->\r\n");
      out.write("\t\t\t");

			  	}
			
      out.write("\t\r\n");
      out.write("\t\t</p>\t\r\n");
      out.write("    </div>\r\n");
      out.write("\t<!-- /Header -->\r\n");
      out.write("\t\r\n");
      out.write("   <!-- Page Content -->\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-lg-12\">\r\n");
      out.write("                <h1 class=\"page-header\">Catalogue de jeux</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-lg-3 col-md-4 col-xs-6 thumb\">\r\n");
      out.write("                <a class=\"thumbnail\" href=\"http://172.16.15.149:3000\" TARGET=\"_blank\">\r\n");
      out.write("                    <img src=\"http://img11.hostingpics.net/pics/195336logobubblespace.png\" alt=\"BubbleSpace\">\r\n");
      out.write("                </a>\r\n");
      out.write("                <p style=\"color:white;\">Affrontez vous et soyer le plus gros de la galaxie dans BubbleSpace!</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-4 col-xs-6 thumb\">\r\n");
      out.write("                <a class=\"thumbnail\" href=\"#\">\r\n");
      out.write("                    <img class=\"img-responsive\" src=\"http://www.tonka3d.com/img/personagem-3d-para-games-prototipos-by-tonka3d.jpg\" alt=\"\">\r\n");
      out.write("                </a>\r\n");
      out.write("                <p style=\"color:white;\">Prochainement disponible!</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-4 col-xs-6 thumb\">\r\n");
      out.write("                <a class=\"thumbnail\" href=\"#\">\r\n");
      out.write("                    <img class=\"img-responsive\" src=\"http://www.actugaming.net/uploads/0a6f99b4408a21fc7bce56fe7129371a.jpg\" alt=\"\">\r\n");
      out.write("                </a>\r\n");
      out.write("                <p style=\"color:white;\">Prochainement disponible!</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-4 col-xs-6 thumb\">\r\n");
      out.write("                <a class=\"thumbnail\" href=\"#\">\r\n");
      out.write("                    <img class=\"img-responsive\" src=\"http://www.mrwallpaper.com/wallpapers/witcher-3-game-1600x900.jpg\" alt=\"\">\r\n");
      out.write("                </a>\r\n");
      out.write("                <p style=\"color:white;\">Prochainement disponible!</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-4 col-xs-6 thumb\">\r\n");
      out.write("                <a class=\"thumbnail\" href=\"#\">\r\n");
      out.write("                    <img class=\"img-responsive\" src=\"http://eskipaper.com/images/free-game-wallpapers-hd-4.jpg\" alt=\"\">\r\n");
      out.write("                </a>\r\n");
      out.write("                <p style=\"color:white;\">Prochainement disponible!</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-4 col-xs-6 thumb\">\r\n");
      out.write("                <a class=\"thumbnail\" href=\"#\">\r\n");
      out.write("                    <img class=\"img-responsive\" src=\"http://www.mrwallpaper.com/wallpapers/bayonetta-2-video-game-1600x900.jpg\" alt=\"\">\r\n");
      out.write("                </a>\r\n");
      out.write("                <p style=\"color:white;\">Prochainement disponible!</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-4 col-xs-6 thumb\">\r\n");
      out.write("                <a class=\"thumbnail\" href=\"#\">\r\n");
      out.write("                    <img class=\"img-responsive\" src=\"http://gamehall.uol.com.br/selectgame/wp-content/uploads/2011/12/the-last-of-us-wallpaper-1600x900.jpg\" alt=\"\">\r\n");
      out.write("                </a>\r\n");
      out.write("                <p style=\"color:white;\">Prochainement disponible!</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-4 col-xs-6 thumb\">\r\n");
      out.write("                <a class=\"thumbnail\" href=\"#\">\r\n");
      out.write("                    <img class=\"img-responsive\" src=\"http://www.mrwallpaper.com/wallpapers/game-gameglobe-1600x900.jpg\" alt=\"\">\r\n");
      out.write("                </a>\r\n");
      out.write("                <p style=\"color:white;\">Prochainement disponible!</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-4 col-xs-6 thumb\">\r\n");
      out.write("                <a class=\"thumbnail\" href=\"#\">\r\n");
      out.write("                    <img class=\"img-responsive\" src=\"http://www.mrwallpaper.com/wallpapers/2013-destiny-game-1600x900.jpg\" alt=\"\">\r\n");
      out.write("                </a>\r\n");
      out.write("                <p style=\"color:white;\">Prochainement disponible!</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-4 col-xs-6 thumb\">\r\n");
      out.write("                <a class=\"thumbnail\" href=\"#\">\r\n");
      out.write("                    <img class=\"img-responsive\" src=\"http://www.wallpaper77.com/upload/DesktopWallpapers/cache/Fallout-3-Wallpaper-7-fallout-3-wallpapers-game-wallpapers-1600x900.jpg\" alt=\"\">\r\n");
      out.write("                </a>\r\n");
      out.write("                <p style=\"color:white;\">Prochainement disponible!</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-4 col-xs-6 thumb\">\r\n");
      out.write("                <a class=\"thumbnail\" href=\"#\">\r\n");
      out.write("                    <img class=\"img-responsive\" src=\"http://www.mrwallpaper.com/wallpapers/bioshock-infinite-game-1600x900.jpg\" alt=\"\">\r\n");
      out.write("                </a>\r\n");
      out.write("                <p style=\"color:white;\">Prochainement disponible!</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <hr>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /.container -->\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("        <div class=\"footer\">\r\n");
      out.write("        <p style=\"text-align:center;\" class=\"text-muted\">I-GAME© by T2ISOFT : <a href=\"http://www.t2isoft.com\">www.t2isoft.com</a></p>\r\n");
      out.write("      </div>  \r\n");
      out.write("<!-- /Footer -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
