/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2015-11-22 14:24:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class registration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- \r\n");
      out.write("/**\r\n");
      out.write(" * @author LearnBySourceCode\r\n");
      out.write(" * Copyright © 2015 LearnBySourceCode.blogspot.com, All Rights Reserved.\r\n");
      out.write(" * \r\n");
      out.write(" */\r\n");
      out.write(" -->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Registration Form</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"./resources/css/registerStyle.css\">\r\n");
      out.write("<script src=\"./resources/js/registration-form-validation.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction validate_exist_email() {\r\n");
      out.write("\t\tvar errorMsg = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errMsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t\tvar uemail = document.getElementById(\"exist_email\");\r\n");
      out.write("\t\tuemail.innerHTML = '<b><span style=\"color: red; font-family: Courier New, Courier, monospace; font-size: small;\">'\r\n");
      out.write("\t\t\t\t+ errorMsg + ' </span></b>';\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"validate_exist_email();\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"register\">\r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t\t<legend>\r\n");
      out.write("\t\t\t\t<h1>Registration</h1>\r\n");
      out.write("\t\t\t</legend>\r\n");
      out.write("\t\t\t<form action=\"RegistrationServlet\" method=\"post\" name=\"registration\"\r\n");
      out.write("\t\t\t\tonSubmit=\"return formValidation();\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<label for=\"username\"><b>Username <span\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"color: white; font-family: Courier New, Courier, monospace; font-size: large;\">*</span></b></label>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"username\" maxlength=\"50\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"username\" required=\"required\"></input>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"err_username\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<label for=\"password\"><b>Password <span\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"color: white; font-family: Courier New, Courier, monospace; font-size: large;\">*</span></b></label>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" name=\"password\" maxlength=\"50\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"password\" required=\"required\"></input>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"err_password\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<label for=\"confirm_password\"><b>Retype Password <span\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"color: white; font-family: Courier New, Courier, monospace; font-size: large;\">*</span></b></label>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" name=\"confirm_password\" maxlength=\"50\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"confirm password\" required=\"required\"></input>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"err_cpassword\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<label for=\"email\"><b>E-mail <span\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"color: white; font-family: Courier New, Courier, monospace; font-size: large;\">*</span></b></label>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"email\" maxlength=\"50\" placeholder=\"email\"\r\n");
      out.write("\t\t\t\t\t\t\trequired=\"required\"></input>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"err_email\"></div>\r\n");
      out.write("\t\t\t\t\t<div id=\"exist_email\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<label for=\"website_url\"><b>Website URL </b></label>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"website_url\" maxlength=\"70\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"website url\"></input>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"err_url\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"55%\"><input type=\"reset\" value=\"Reset\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"btn btn-primary btn-block btn-large\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input style=\"width: 190px;\" type=\"submit\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"Submit\" class=\"btn btn-primary btn-block btn-large\" /></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\"><a href=\"login.jsp\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"color: yellow; text-decoration: underline;\">Already Registered</span></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"text-align: center;\">\r\n");
      out.write("\t\t<a href=\"http://www.learnbysourcecode.blogspot.com/\" target=\"_blank\"><span\r\n");
      out.write("\t\t\tstyle=\"color: white; font-family: monospace; font-size: x-small;\">Copyright\r\n");
      out.write("\t\t\t\t© 2015 LearnBySourceCode.blogspot.com, All Rights Reserved.</span></a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
